// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pedido.Data;

#nullable disable

namespace Pedido.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pedido.Models.ItemPedido", b =>
                {
                    b.Property<int>("ItemPedidoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemPedidoKey"));

                    b.Property<int?>("PedidoClientePedidoKey")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ItemPedidoKey");

                    b.HasIndex("PedidoClientePedidoKey");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("Pedido.Models.PedidoCliente", b =>
                {
                    b.Property<int>("PedidoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PedidoKey"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PedidoKey");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Pedido.Models.ItemPedido", b =>
                {
                    b.HasOne("Pedido.Models.PedidoCliente", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoClientePedidoKey");
                });

            modelBuilder.Entity("Pedido.Models.PedidoCliente", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
